import Head from 'next/head';
import Navbar from '../../components/Navbar';
import { useState } from 'react';
import Newsletter from '../../components/Newsletter';
import Footer from '../../components/Footer';
import { collection, getDocs, query, orderBy, limit } from "firebase/firestore";
import { format } from 'date-fns';
import { db } from '../../components/firebase';
import { useRouter } from 'next/router';

export default function Home(props) {
  
  // change this name
  const { output } = props;
  const router = useRouter();

  const [selectedTag, setSelectedTag] = useState( () => {
    if(router.query["tag"])
      return router.query["tag"];
    else
      return 'All';
  });
  
  // extract tags from all articles object
  function getTags () {
    var temp = [];
    output.map( article => {
      if(!temp.includes(article.tag))
        temp.push(article.tag)
    })
    return (temp);
  }

  return (
    <>
      <Head>
        <meta charSet='utf-8' />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
        <meta name="description" content="Generated by create next app" />

        <title>Francesco Barbieri - Archive</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <center>
        <div className='wrapper'>
          <Navbar />
          <Newsletter />
          <Footer />
        </div>
      </center>
    </>
  )
}

// Gestire potenziali errori da questa funzione

export async function getServerSideProps () {

  try {
      const q = query(collection(db, 'articles'), orderBy("date", "desc"));
      const querySnapshot = await getDocs(q);
  
      let output = [];
  
      querySnapshot.docs.map( doc => {
        output.push(
              {
                  id: doc.id,
                  date: format(doc.data().date.toDate() , 'MMMM d, yyyy'),
                  tag: doc.data().tag,
                  title: doc.data().title,
                  preview: doc.data().preview,
                  mainImg: doc.data().mainImg
              }
          )
      })

      return { props: {output}}
  } catch(e) {
      return { props: {}}
  }

}