import Head from 'next/head';
import Navbar from '../components/Navbar';
import SectionTitle from '../components/SectionTitle';
import { robotoSlab } from '../components/fonts';

export default function About() {
  return (
    <>
      <Head>
        <meta charSet='utf-8' />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
        <meta name="description" content="Generated by create next app" />

        <title>Francesco Barbieri - About</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <center>
        <main className='wrapper'>
          <Navbar />
          <section>
            <SectionTitle
              title="About me"
              icon="about"
            />
            <h3 className={robotoSlab.className}>More info about me</h3>
            <SectionTitle
              title="Recommended readings"
              icon="readings"
            />
            <p>This list was updated in <b>February 2023.</b></p>
          </section>
        </main>
      </center>
    </>
  )
}
  