import Head from 'next/head';
import ArticlesCollection from '../components/ArticlesCollection';
import Navbar from '../components/Navbar';
import TagSelector from '../components/TagSelector';
import { useState } from 'react';
import Newsletter from '../components/Newsletter';
import Footer from '../components/Footer';

export default function Home() {
  const [selectedTag, setSelectedTag] = useState();

  return (
    <>
      <Head>
        <meta charSet='utf-8' />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
        <meta name="description" content="Generated by create next app" />

        <title>Francesco Barbieri - Archive</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <center>
        <div className='wrapper'>
          <Navbar />
          <TagSelector setTag={setSelectedTag} currentTag={selectedTag}/>
          <ArticlesCollection />
          <Newsletter />
          <Footer />
        </div>
      </center>
    </>
  )
}