import Head from "next/head";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import Newsletter from "../components/Newsletter";
import { collection, getDocs, query, orderBy, limit } from "firebase/firestore";
import { format } from "date-fns";
import { db } from "../components/firebase";
import SectionTitle from "../components/SectionTitle";
import ArticlesCollection from "../components/ArticlesCollection";

export default function Home(props) {
    const { output } = props;

    return (
        <>
            <Head>
                <meta charSet="utf-8" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />

                <meta
                    name="description"
                    content="Generated by create next app"
                />

                <title>Francesco Barbieri</title>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <center>
                <div className="wrapper">
                    <Navbar />
                    <section>
                        <SectionTitle title="Latest articles" icon="latest" />
                        <ArticlesCollection articles={output} />
                    </section>
                    <Newsletter />
                    <Footer />
                </div>
            </center>
        </>
    );
}

// Gestire potenziali errori da questa funzione
export async function getServerSideProps() {
    try {
        const q = query(
            collection(db, "articles"),
            orderBy("date", "desc"),
            limit(3)
        );
        const querySnapshot = await getDocs(q);

        let output = [];

        querySnapshot.docs.map((doc) => {
            output.push({
                id: doc.id,
                date: format(doc.data().date.toDate(), "MMMM d, yyyy"),
                tag: doc.data().tag,
                title: doc.data().title,
                preview: doc.data().preview,
            });
        });

        return { props: { output } };
    } catch (e) {
        return { props: e };
    }
}
